services:
  backend:
    build:
      target: deps
    command: sh -c "npx prisma generate && npm run start:dev"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
      CHOKIDAR_INTERVAL: "1000"

  frontend:
    build:
      target: deps
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development